apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    app: {{ .Values.metadata.labels.app }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.0-alpine
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: {{ .Values.volumeMounts.mountPath }}
            subPath: {{ .Values.volumeMounts.subPath }}
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:{{ .Values.nginx.tag }}
        env:
          - name: SCRAPE_URI
            value: {{ .Values.env.value }}
          - name: NGINX_RETRIES
            value: "10"
        ports:
        - containerPort: 9113
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
