apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.labels.app }}
spec:
  selector:
    app: {{ .Values.service.labels.app}}
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: nginx-exporter
      port: 9113
      protocol: TCP
      targetPort: 9113
