dist: bionic
language: bash
sudo: required
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-platform-tests/2020-04/run.sh
    | bash
notifications:
  slack:
    rooms:
      secure: AZ23LoavCzbs5bLIaJpoVYZDFgg3lYZW0RVqU1Rbzfvf0M038+8ZaEXqszMOKxmJnVyQ0VScM/fK0WJLQ/8gJAHE5YtEdwHv/0BP5E0BktwaNblF2b2sBhFjY4CWC9oQWD+o5zZjJCT/vKU0MaGVIWRN5FqjZOxOrCHO5t6mCOCmvNlfKD6t82//7OXLl2KXET1jPPHy3gEbdKfJZt50kd4XZEKuxGLlGlVbtjI6VPQ1sSJt95WGBml+b4OICIsnCvKThZK95knZrsvoUyDMB8KXocWv91wvi2qLsXhbMKdlhRlmVZHGaB2hQctB4sp69GAUJtMxjpev/JYjI4POtL7W0BgoCMpObxE+L8MoU8xVblviUtbUneZ0hKHhB2lUE+umvcuxiHE+taVFAb85PtOgIe+H5rAe7XOL/1sluuX1jIa/mlWa4bHqYXJewaRojxGDhsgWb76KxBjdFe6QNO230jVUVIGUi8N5RvLRCpAlnnw2lC0d4QgJi8p/6bbo+5II9WisYeDc7miniYp6q4lVHyApTgy9WqKI9Nf1aB2MRVNCp1DXWHteA2tWSMyVprYLb9la/h+4h9qUyNKHTFUri8NcCyVZqpzL9ir08eh5Xd/xIMnbvUduxFvk7Ib2OeQ7jvElTjk+dsz6keUs1R026QT0bP/+ABdOkV/VfI0=
