dist: bionic
language: bash
sudo: required
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-platform-tests/2020-04/run.sh
    | bash
notifications:
  slack:
    rooms:
      secure: epRXOAPZsOI3XVuTVTVxtGhBVTLlc4n19GiNJqBFtVDVzMot1elVI2xgVVSuiHs7FgiedTVVcPGwJvt5YhMT8z6/rFjy9yCkQKud6VWG6iXQjYxOzKdBitxGqpvaW5tq07IGxrY50bzp9lbhihXs2dwThTjD+2DFnrXlp1gDH9Qb6WBsc+kZ4mZGcdjfnSNQTeanToEGiHMbxmXnfHYxq/I+XuIMCkn01u06vMAloU/29xJ33Qsk2lYcYYdn3MoIEkJxTBVDS1vCy/LovPndw2DexGN9yWWs3FHDGXsIQ4gbrdKNgMkNRLiLBpSCQql0R6wuRh6gggDvCNosSb1JnVe9Ii3H75WsMbL3hezhuG4L+VxMTZ9lCRKMuAVjKimMsarN2zwMlMgxzk8pfUv3oFxUydXe0p+zV6pphiI4GrIVM6xe8WqnNWEQ5GVTa5Cu1mK4oGRDnH5X+uB76tu6xh0wybpm0NYz3LoU06bGYaUEifs+4TMS2OK/1XCzZTlFoCZwk7T0NLWjS14jeir5L4ZM43KhICw5vekDdOZv8iQ0OZLRUZ1GrIhMO8fH4jgarbnyvb4BMNYNC/v3wqRH5eSDdzF2/+IU6UVZ/gdVquiD9ZVmjc1D5GAezvJwRwI6bSXuxCoMX2wxXgtYwdvDEq9JAv/kmNRpJIGVWd6dn5Q=
