apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob
  namespace: default
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   # "namespace" omitted since ClusterRoles are not namespaced
#   name: bob
# rules:
#   - apiGroups: [""]
#     resources: ["deployments"]
#     verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: admin-bob
# subjects:
#   - kind: ServiceAccount
#     name: bob
#     namespace: default
#     apiGroup: ""
# roleRef:
#   kind: ClusterRole
#   name: bob-reader
#   apiGroup: rbac.authorization.k8s.io
