kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bob-permissive-role
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - permissive
    verbs:
      - use
