kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bob-default
subjects:
  - kind: ServiceAccount
    name: bob
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: bob-permissive-role
  apiGroup: rbac.authorization.k8s.io
