backend:
  type: es
  es:
    host: elasticsearch-master
rawConfig: |
  @INCLUDE fluent-bit-service.conf
  @INCLUDE fluent-bit-input.conf
  @INCLUDE fluent-bit-filter.conf
  @INCLUDE fluent-bit-output.conf

  # [FILTER]
  #     Name     modify
  #     Match    *
  #     # Remove   time
  #     # Remove   @timestamp

filter:
  #   # If true, check to see if the log field content is a JSON string map, if so,
  #   # it append the map fields as part of the log structure.
  #   # https://github.com/fluent/fluent-bit/issues/628
  #   mergeJSONLog: false
  #   # If set, all unpacked keys from mergeJSONLog (Merge_Log) will be packed under
  #   # the key name specified on mergeLogKey (Merge_Log_Key)
  mergeLogKey: "app"
tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule
