prometheus:
  ingress:
    enabled: true
    annotations: { kubernetes.io/ingress.class: nginx }
    path: /
    hosts:
      - prometheus.34.90.81.164.xip.io
  prometheusSpec:
    tolerations:
      - key: node-role
        operator: Equal
        value: infra
        effect: NoSchedule
    serviceMonitorSelectorNilUsesHelmValues: false
grafana:
  ingress:
    enabled: true
    annotations: { kubernetes.io/ingress.class: nginx }
    path: /
    hosts:
      - grafana.34.90.81.164.xip.io
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki:3100/
      access: proxy
