apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  template:
    spec:
      containers:
        - name: server
          env:
            - name: REDIS_ADDR
              value: "redis-cart:6379"
